name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: zainhmdd
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'zainhmdd'
          git config --global user.email 'zainabahmad10@student.cs.unida.gontor.ac.id'
          git add .
          git commit -m "generate snake"
          git push
